networks:
  swc-network:
    driver: bridge

services:
  cms:
    container_name: swc_cms
    build:
      context: ./drupal
      dockerfile: cms.Dockerfile
    ports:
      - 80:80
    expose:
      - 80
    volumes:
      - ./drupal/files:/opt/drupal/web/sites/default/files
      - ./drupal/config:/opt/drupal/config
      - ./drupal/modules/custom:/opt/drupal/web/modules/custom
      - ./drupal/themes/custom:/opt/drupal/web/themes/custom
      - ./drupal/composer.json:/opt/drupal/composer.json
      - ./drupal/composer.lock:/opt/drupal/composer.lock
      - ./drupal/settings.local.php:/opt/drupal/web/sites/default/settings.local.php
    networks:
      - swc-network
  db:
    container_name: swc_db
    image: arm64v8/mysql
    environment:
      MYSQL_DATABASE: 'swc_squatober'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - 3306
    restart: always
    volumes:
      - ./data/database/data:/var/lib/mysql
    networks:
      - swc-network 
